`cabal-install` is built from sources using the ghc (haskell compiler)
+ Build still fails because:

```
Network/Socks5/Lowlevel.hs:10:1: error:
    Failed to load interface for ‘Network.BSD’
    Use -v to see a list of the files searched for.
cabal: Failed to build socks-0.5.6 (which is required by exe:pandoc-crossref
from pandoc-crossref-0.3.1.0, pandoc-citeproc-0.14.3.1 and others). See the
build log above for details.
```